source 'http://rubygems.org'

gem 'certified'
gem 'cucumber'
gem 'data_magic'
gem 'faker'
gem 'fig_newton'
gem 'page_navigation'
gem 'page-object'
gem 'pretty_face'
gem 'rake'
gem 'RDee'
gem 'require_all'
gem 'restforce'
gem 'rspec'
gem 'psych'
gem 'selenium-webdriver', '>=2.45.0.dev3'